set guioptions=aegikmrt
set guicursor=a:blinkon0

if has("gui_running")
    if has("gui_macvim")
        set guifont=-monospace-:h15
    elseif has("x11")
        set guifont=Monospace\ Regular\ 11
    endif
endif

map <silent> <F11> :call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")<CR>
