#!/usr/bin/env bash
# shellcheck source=/dev/null

# brew is not on the default PATH on Apple Silicon; shellenv sets PATH and all HOMEBREW_* vars
for __brew in /opt/homebrew/bin/brew /usr/local/bin/brew; do
  [ -x "$__brew" ] && eval "$("$__brew" shellenv)" && break
done
unset __brew
if [ -n "$HOMEBREW_PREFIX" ]; then
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]
  then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*
    do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

if [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]]; then
    #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
    export SDKMAN_DIR="$HOME/.sdkman"
    # shellcheck source=/dev/null
    source "$HOME/.sdkman/bin/sdkman-init.sh"
fi
