#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2154
if [ "$__os_family" = "Mac" ]; then
    alias df='df -H'
    alias du='du --si -c -A -B 1'
    alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
    alias ls='ls -G -h -D "%Y %b %e %H:%M"'
    alias tac='tail -r'
    alias time='/usr/bin/time -hlp'
    alias restartTouchBar='sudo pkill TouchBarServer;sudo killall "ControlStrip"'
else
    alias df='df -TkH'
    alias du='du -bc --si'
    alias ls='ls --si --color=auto --time-style="+%Y %b %e %H:%M"'
    if command -v xclip &>/dev/null; then
        alias pbcopy='xclip -selection clipboard'
    elif command -v xsel &>/dev/null; then
        alias pbcopy='xsel --clipboard --input'
    fi
fi

alias cp='cp -i'
alias dust='dust --apparent-size'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'
alias grep='grep --color=auto'
alias la='ls -Al'
alias less='less -rMi -x4' # lesskey file is disabled on MacOS
alias ll='ls -l'
alias lt='ls -Alrt'
alias mv='mv -i'
alias rm='rm -i'
alias rmlinks='find . -maxdepth 1 -type l -exec rm -f "{}" \;'
alias tree='tree -C'
alias xmllint='xmllint --format'
alias zgrep='zgrep --color=auto'
alias rg='rg --colors "match:fg:74" --colors "path:fg:219" --colors "line:fg:36"'

if command -v ncal &>/dev/null; then
    alias ncal='ncal -Mb'
    ! [ "$__os_family" = "Mac" ] && alias cal='ncal -Mb'
elif ! [ "$__os_family" = "Mac" ]; then
    alias cal='cal -m'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'
alias ...........='cd ../../../../../../../../../..'

alias gcp='git pull; git commit; git push'
alias glog='git log --all --stat --summary'
alias gsl='git stash list'

alias ctags='ctags --extra=+f --langdef=file --langmap='"'"'file:.xsd.xml.xsl.jsp.tag.properties.js'"'"' --exclude=target --exclude=*.class -R'

alias vimdiff='nvim -d'
alias view='nvim -R'
alias vim='nvim'

alias viewASN1DER='openssl asn1parse -inform DER -i -in'
alias viewASN1PEM='openssl asn1parse -inform PEM -i -in'
alias viewCRL='openssl crl  -text -noout -inform DER -in'
alias viewDER='openssl x509 -text -noout -inform DER -in'
alias viewNET='openssl x509 -text -noout -inform NET -in'
alias viewP12='openssl pkcs12 -info -in'
alias viewPEM='openssl x509 -text -noout -inform PEM -in'
alias viewPFX='certutil -dump'
alias viewPRIVEC='openssl ec -text -noout -in'
alias viewPRIVRSA='openssl rsa -text -noout -in'
alias viewPUBRSA='openssl  rsa -text -noout -in -pubin'

if command -v xset &>/dev/null; then
    if [[ $(xset q) == *"Server does not have the DPMS Extension"* ]]; then
        alias scroff='busctl --user call org.gnome.Shell /org/gnome/ScreenSaver org.gnome.ScreenSaver SetActive b true'
    else
        alias scroff='xset dpms force off'
    fi
fi

alias hexdump='hexdump -C'

if command -v jq &>/dev/null; then
    alias jq="jq -S"
elif command -v python -m json.tool &>/dev/null; then
    alias js="python -m json.tool"
fi

alias httpsforw='sudo iptables -t nat -A OUTPUT -o lo -p tcp -j REDIRECT -d localhost --dport 443 --to-ports 8443'
alias rmhttpsforw='sudo iptables -t nat -D OUTPUT -o lo -p tcp -j REDIRECT -d localhost --dport 443 --to-ports 8443'

alias hc='history -c'

alias clock='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &'
alias cmatrix='cmatrix -b -s -C magenta -u 9'
alias ws='$HOME/dotfiles/bin/tmux_workspace.sh'
