#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2154
alias rm='rm -i'
alias rmlinks='find . -maxdepth 1 -type l -exec rm -f "{}" \;'
alias mv='mv -i'
alias cp='cp -i'

if [ "$__os_family" = "Mac" ]; then
    alias df='df -kh'
    alias du='du -ch'
else
    alias df='df -TkH'
    alias du='du -bc --si'
fi

if [ "$__os_family" = "Mac" ]; then
    alias ls='ls -G -h -D "%Y %b %e %H:%M"'
    alias tac='tail -r'
    alias time='/usr/bin/time -hlp'
    alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
else
    alias ls='ls --si --color=auto --time-style="+%Y %b %e %H:%M"'
fi
alias la='ls -Al'
alias ll='ls -l'
alias lt='ls -Alrt'

alias less='less -rMi'
alias more='more -r'
alias ncal='ncal -Mb'
if hash ncal &>/dev/null; then
    if ! [ "$__os_family" = "Mac" ]; then
        alias cal='ncal -Mb'
    fi
elif ! [ "$__os_family" = "Mac" ]; then
    alias cal='cal -m'
fi
alias xmllint='xmllint --format'

alias grep='grep --color=auto'
alias zgrep='zgrep --color=auto'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'
alias ...........='cd ../../../../../../../../../..'

alias sci='svn ci'
alias gsl='git stash list'
alias gcp='git pull; git commit; git push'
alias glog='git log --all --stat --summary'

alias ctags='ctags --extra=+f --langdef=file --langmap='"'"'file:.xsd.xml.xsl.jsp.tag.properties.js'"'"' --exclude=target --exclude=*.class -R'

alias vd='vimdiff'
alias view='vim -R'

alias viewP12='openssl pkcs12 -info -in'
alias viewPEM='openssl x509 -text -noout -inform PEM -in'
alias viewDER='openssl x509 -text -noout -inform DER -in'
alias viewNET='openssl x509 -text -noout -inform NET -in'
alias viewPUBRSA='openssl rsa -text -noout -pubin -in'
alias viewPRIVRSA='openssl rsa -text -noout -in'
alias viewPFX='certutil -dump'
alias viewASN1PEM='openssl asn1parse -inform PEM -i -in'
alias viewASN1DER='openssl asn1parse -inform DER -i -in'
alias viewCRL='openssl crl -text -noout -inform DER -in'

if hash xset &>/dev/null; then
    if [[ $(xset q) == *"Server does not have the DPMS Extension"* ]]; then
        alias scroff='busctl --user call org.gnome.Shell /org/gnome/ScreenSaver org.gnome.ScreenSaver SetActive b true'
    else
        alias scroff='xset dpms force off'
    fi
fi

alias hexdump='hexdump -C'

if command -v jq &>/dev/null; then
    alias jq="jq -S"
elif command -v python -m json.tool &>/dev/null; then
    alias js="python -m json.tool"
fi

alias httpsforw='sudo iptables -t nat -A OUTPUT -o lo -p tcp -j REDIRECT -d localhost --dport 443 --to-ports 8443'
alias rmhttpsforw='sudo iptables -t nat -D OUTPUT -o lo -p tcp -j REDIRECT -d localhost --dport 443 --to-ports 8443'

alias hc='history -c'

alias clock='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &'
alias cmatrix='cmatrix -b -s -C magenta -u 9'
