#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2034

# High Intensty
#Black='0;90'
#Red='0;91'
#Green='0;92'
#Yellow='0;93'
#Blue='0;94'
#Purple='0;95'
#Cyan='0;96'
#White='0;97'

SkyBlue3='0;38;5;74'
LightSkyBlue3='0;38;5;110'
PaleGreen3='0;38;5;114'
DeepPink3='0;38;5;162'
Plum2='0;38;5;183'
#Khaki1='0;38;5;228'

# Bold High Intensty
#BBlack='1;90'
#BBlue='1;94'
#BCyan='1;96'
#BGreen='1;92'
#BPurple='1;95'
#BRed='1;91'
#BWhite='1;97'
BYellow='1;38;5;11'
BIndianRed='1;38;5;167'
BGrey50='1;38;5;244'

# Underline High Intensty
#UBlack='4;90'
#URed='4;91'
#UGreen='4;92'
#UYellow='4;93'
#UBlue='4;94'
#UPurple='4;95'
#UCyan='4;96'
#UWhite='4;97'

# Reversed High Intensty
#RBlack='7;90'
#RBlue='7;94'
#RCyan='7;96'
#RGreen='7;92'
#RPurple='7;95'
#RRed='7;91'
#RWhite='7;97'
#RYellow='7;93'
RIndianRed='7;38;5;131'
RTurquoise2='7;38;5;45'
