#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2034

### Set
#0 = default colour
#1 = bold
#2 = dim
#4 = underlined
#5 = flashing/blink text
#7 = reverse field
#8 = hidden (useful for passwords)

### Foreground
#30 = black
#31 = red
#32 = green
#33 = orange
#34 = blue
#35 = purple
#36 = cyan
#37 = grey
#39 = default foreground color
#90 = dark grey
#91 = light red
#92 = light green
#93 = yellow
#94 = light blue
#95 = light purple
#96 = turquoise
#97 = white

### Background
#40  = black background
#41  = red background
#42  = green background
#43  = orange background
#44  = blue background
#45  = purple background
#46  = cyan background
#47  = grey background
#49  = default background color
#100 = dark grey background
#101 = light red background
#102 = light green background
#103 = yellow background
#104 = light blue background
#105 = light purple background
#106 = turquoise background
#107 = white background

ResetColor='\e[0m'

# High Intensty
#Black='\e[0;49;90m'
#Blue='\e[0;49;94m'
#Cyan='\e[0;49;96m'
#Green='\e[0;49;92m'
#Purple='\e[0;49;95m'
#Yellow='\e[0;49;93m'
DodgerBlue2='\e[0;38;5;27m'
PaleGreen3='\e[0;38;5;114m'
Red='\e[0;38;5;9m'
White='\e[0;38;5;15m'

# Bold High Intensty
#BBlue='\e[1;49;94m'
#BCyan='\e[1;49;96m'
#BGreen='\e[1;49;92m'
#BPurple='\e[1;49;95m'
#BRed='\e[1;49;91m'
#BWhite='\e[1;49;97m'
#BYellow='\e[1;49;93m'
BGrey27='\e[1;38;5;238m'

# Underline High Intensty
#UBlack='\e[4;49;90m'
#UBlue='\e[4;49;94m'
#UCyan='\e[4;49;96m'
#UGreen='\e[4;49;92m'
#UPurple='\e[4;49;95m'
#URed='\e[4;49;91m'
#UWhite='\e[4;49;97m'
#UYellow='\e[4;49;93m'
